name: Deploy to Heroku

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest    
    env:
      config: 'Release'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100          
    - name: Install dependencies
      run: dotnet restore    
    - name: Build
      run: dotnet build --configuration $config --no-restore                  
    - name: Test     
      run: dotnet test --no-restore --no-build --configuration $config       
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:push -a zbyrach-api web 
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: cd src/Zbyrach.Api && heroku container:release -a zbyrach-api web 