name: Deploy API

on: 
  push:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
    - name: Dotnet Publish
      run: dotnet publish ./src/RussianSitesStatus/RussianSitesStatus.csproj -c Release -o deploy
    - name: Edit property string value in appsettings.json
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'DATABASE_URL'
        valuetoset: ${{ secrets.DATABASE_URL }}
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: /home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/
        remote: /var/www/mss-api
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo systemctl restart mss-api
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.PRIVATE_KEY }}