name: Deploy Worker

on: 
  push:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.400
    - name: Dotnet Publish
      run: dotnet publish ./src/RussianSitesStatus/RussianSitesStatus.csproj -c Release -o deploy
    
    - name: Update DATABASE_URL setting
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'DATABASE_URL'
        valuetoset: ${{ secrets.DATABASE_URL }}
    - name: Update ARCHIVE_AT setting
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'ARCHIVE_AT'
        valuetoset: ''
    - name: Update CALCULATE_STATISTICS_AT setting
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'CALCULATE_STATISTICS_AT'
        valuetoset: ''
    - name: Update SITES_SYNC_INTERVAL setting
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'SITES_SYNC_INTERVAL'
        valuetoset: '-1'    
    - name: Update MEMORY_DATA_SYNC_INTERVAL setting
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'MEMORY_DATA_SYNC_INTERVAL'
        valuetoset: '-1'
    - name: Update SITE_CHECK_INTERVAL setting
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'SITE_CHECK_INTERVAL'
        valuetoset: '600'
    - name: Update MAX_SITES_IN_QUEUE setting
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'MAX_SITES_IN_QUEUE'
        valuetoset: '200'
    - name: Update MAX_SITES_IN_WAIT_QUEUE setting
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'MAX_SITES_IN_WAIT_QUEUE'
        valuetoset: '50'
    - name: Update SITE_CHECK_PAUSE_BEFORE_START setting
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'SITE_CHECK_PAUSE_BEFORE_START'
        valuetoset: '5'
    - name: Update SITE_CHECK_SKIP_TAKE setting
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '/home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/appsettings.json'
        keyname1: 'SITE_CHECK_SKIP_TAKE'
        valuetoset: '0,2000'

    - name: Copy via SSH
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: /home/runner/work/russian-sites-status-api/russian-sites-status-api/deploy/
        remote: /var/www/mss-worker
        host: ${{ secrets.HOST_WORKER }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo systemctl restart mss-worker
        host: ${{ secrets.HOST_WORKER }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.PRIVATE_KEY }}